# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('developer', models.CharField(max_length=20)),
                ('release_date', models.DateField(verbose_name='date published')),
                ('esrb_rating', models.CharField(choices=[('E', 'EVERYONE'), ('T', 'TEEN'), ('M', 'MATURE')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=20)),
                ('date_found', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('player_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_pool', models.IntegerField()),
                ('first_prize', models.IntegerField()),
                ('second_prize', models.IntegerField()),
                ('third_prize', models.IntegerField()),
                ('prize_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('logo', models.URLField()),
                ('team_location', models.CharField(max_length=20)),
                ('team_coach', models.CharField(max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esports.Game')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esports.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourney_name', models.CharField(max_length=20)),
                ('tourney_date', models.DateField()),
                ('participants', models.IntegerField()),
                ('first_place', models.CharField(max_length=20)),
                ('second_place', models.CharField(max_length=20)),
                ('third_place', models.CharField(max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esports.Game')),
            ],
        ),
        migrations.AddField(
            model_name='prize',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esports.Tournament'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esports.Team'),
        ),
    ]
